# Rights declaration file
# For more information about syntax and structure see here:
# https://github.com/Splamy/TS3AudioBot/wiki/Rights

"+" = [
	# Basic stuff
	"cmd.help.*",
	"cmd.kickme.*",
	
	# Getting song info
	"cmd.piosenka",
	"cmd.loop",

	# Conditionals and basic scripting
	"cmd.print",
	"cmd.xecute",
	"cmd.getmy.*",
	"cmd.json.*",
	"cmd.bot.use",
	"cmd.config.can",
]

# Admin rule
[[rule]]
	# Set your admin Group Ids here, ex: [ 13, 42 ]
	groupid = []
	# And/Or your admin Client Uids here
	useruid = [ "MTx2YJYbZ2I78oWRlsWCdeEkWlE=" ]
	# By default treat requests from localhost as admin
	ip = [ "127.0.0.1", "::1" ]

	"+" = "*"

# Playing rights
[[rule]]
	# Set Group Ids you want to allow here, ex: [ 13, 42 ]
	groupid = []
	# And/Or Client Uids here, ex [ "uA0U7t4PBxdJ5TLnarsOHQh4/tY=", "8CnUQzwT/d9nHNeUaed0RPsDxxk=" ]
	useruid = []
	# Or remove groupid and useruid to allow for everyone

	"+" = [
		# Play controls
		"cmd.play",
		"cmd.zatrzymaj",
		"cmd.stop",
		"cmd.przewin",
		"cmd.volume",

		# Playlist management
		"cmd.list.*",
		"cmd.clear",
		"cmd.poprzednia",
		"cmd.kolejna",
		"cmd.random.*",
		"cmd.loop.*",

	]
